from jetsontk1:base
WORKDIR /workspace

COPY src src

RUN wget https://developer.nvidia.com/embedded/dlc/l4t-Jetson-TK1-Gstjpeg-Sources-R21-5
RUN wget https://developer.nvidia.com/embedded/dlc/l4t-Jetson-TK1-GstEGL-Sources-R21-5
RUN tar xvf l4t-Jetson-TK1-Gstjpeg-Sources-R21-5
RUN tar xvf l4t-Jetson-TK1-GstEGL-Sources-R21-5

